name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      # Step to create gh_pat.key file with the GitHub token
      - name: Create GitHub PAT file
        run: |
          mkdir -p secrets
          echo "${{ secrets.GITHUB_TOKEN }}" > secrets/gh_pat.key
        # Alternatively, use a custom PAT if stored as a repo secret:
        # echo "${{ secrets.GH_PAT }}" > secrets/gh_pat.key

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: . # The root location of your Astro project inside the repository.
          # node-version: 20 # Optional: Specify Node version if different from default.
          # package-manager: pnpm@latest # Optional: Specify package manager if different from default.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Optional cleanup step to remove secrets/gh_pat.key
      - name: Clean up token file
        run: rm -f secrets/gh_pat.key
